// Builds index.html from the shared app's own page (core/index.html) --
// run it after updating the core submodule, so script versions, viewer
// markup etc. always match the core version in use:
//   node tools/build-index.js
// Only what differs for Digital logbooks is changed:
//  - <base href="core/">: every relative URL in the shared page (scripts,
//    styles, images, the 3D model parts) resolves into the core submodule;
//    this app's own files are referenced from the site root instead
//  - title / header / home-screen name, icons and manifest
//  - config.js (window.APP_CONFIG) loaded before the shared scripts
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
let html = fs.readFileSync(path.join(ROOT, "core", "index.html"), "utf8");

function rep(pattern, replacement) {
  const before = html;
  html = html.replace(pattern, replacement);
  if (html === before) throw new Error("core/index.html changed -- pattern not found: " + pattern);
}

rep(/<meta charset="UTF-8">/, '<meta charset="UTF-8">\n<!-- GENERATED by tools/build-index.js from core/index.html -- edit that script, not this file. -->\n<base href="core/">');
rep(/<title>[^<]*<\/title>/, "<title>Digital logbooks</title>");
rep(/<link rel="icon" type="image\/png" sizes="32x32" href="[^"]*">/, '<link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32.png?v=1">');
rep(/<link rel="icon" type="image\/png" sizes="192x192" href="[^"]*">/, '<link rel="icon" type="image/png" sizes="192x192" href="/icons/icon-192.png?v=1">');
rep(/<link rel="apple-touch-icon" href="[^"]*">/, '<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png?v=1">');
rep(/<link rel="manifest" href="[^"]*">/, '<link rel="manifest" href="/manifest.webmanifest?v=1">');
rep(/<meta name="apple-mobile-web-app-title" content="[^"]*">/, '<meta name="apple-mobile-web-app-title" content="Logbooks">');
// The title, after the app logo (this app's own icon instead).
rep(/<h1><img class="app-logo" src="[^"]*" alt="">Rollcage assessment tool /, '<h1><img class="app-logo" src="/icons/icon-192.png?v=1" alt="">Digital logbooks ');
// The app's configuration has to load before every shared script.
rep(/(<script src="version\.js)/, '<script src="/config.js?v=' + fs.statSync(path.join(ROOT, "config.js")).mtimeMs.toFixed(0) + '"></script>\n$1');

fs.writeFileSync(path.join(ROOT, "index.html"), html);
console.log("Wrote index.html from core/index.html");
